name = "PicoSAT"
uuid = "ff2beb65-d7cd-5ff1-a187-74671133a339"
repo = "https://github.com/jakebolewski/PicoSAT.jl.git"
version = "0.3.4"

[deps]
PicoSAT_jll = "e78fa76d-a187-569f-aede-ad11521a2edf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.6"
